### PR TITLE
expect_lint() improvement

### PR DESCRIPTION
**Pull request by fangly**

### CODE REVIEW

**Comment by jimhester** [comment]
I think this is fine, but really we should remove the file handing entirely and modify the tests to lint a text by ending with a newline. e.g.

```r
lintr::lint("a = b\n")
#> <text>:1:3: style: Use <-, not =, for assignment.
#> a = b
```

**Comment by fangly** [comment]
Thanks Jim. I now understand the undocumented piece of code in `lint()`.
I recorded your improvement suggestion at #234; this will be a task for another day. 
I'll let you merge this PR.

**Comment by fangly** [comment]
Hi Jim,
I found out that it was practically impossible to check the "ranges" of a lint using `expect_lint()`. I have now pushed a few changes in this PR to allow it. Additionally, `expect_lint` is now exported.
Cheers,
Florent

**Comment by jimhester** [comment]
LGTM, thank you!

**Pull request merged**
