### PR TITLE
simplify temporary language settings

### PR DESCRIPTION
**Pull request by MichaelChirico**
Originally wrote this because I noticed another place where we relied on English locale:

https://github.com/jimhester/lintr/blob/9104a004d50c66d3d77cc4e0d4a2c83067f8b43a/R/get_source_expressions.R#L89

But that's covered by #663 already.

Anyway, I think this approach looks nicer. Considered an approach like `with_lang("en", {...})` but the expressions within `{...}` would be huge, don't think it would actually be better.

Also note that before, we weren't actually restoring `LANGUAGE` in the event that it was currently unset, e.g.

```
ORIG = Sys.getenv("LANGUAGE", unset=NA)

Sys.unsetenv("LANGUAGE")

old = Sys.getenv("LANGUAGE")
# do stuff
Sys.setenv(LANGUAGE = old)

# initially, LANGUAGE was unset, now it's set equal to nothing
Sys.getenv("LANGUAGE", unset=NA)
# [1] ""

# true reset. Sys.setenv(LANGUAGE = NA) actually sets "NA"
if (is.na(ORIG)) Sys.unsetenv("LANGUAGE") else Sys.setenv(LANGUAGE = ORIG)
```

### CODE REVIEW

**Comment by AshesITR** [comment]
Are you sure the current behaviour isn't resetting env?

```
"LANGUAGE" %in% names(Sys.getenv())
> [1] FALSE
Sys.setenv(LANGUAGE = "en")
"LANGUAGE" %in% names(Sys.getenv())
> [1] TRUE
Sys.setenv(LANGUAGE = "")
"LANGUAGE" %in% names(Sys.getenv())
> [1] FALSE
```

Tested on R 4.0.3 @ Windows 10.

Also, if we do make a helper, we should use it in all places (I remember `R/expect_lint.R` and `tests/testthat/test-error.R`)

**Comment by MichaelChirico** [comment]
This might be a platform-dependent thing:

```
Sys.unsetenv("LANGUAGE")
"LANGUAGE" %in% names(Sys.getenv())
# [1] FALSE
Sys.setenv(LANGUAGE="")
"LANGUAGE" %in% names(Sys.getenv())
# [1] TRUE
```

**Comment by AshesITR** [comment]
Okay then we should fix it in all places. Thanks for pointing it out!

**Comment by AshesITR** [comment]
#670 causes spurious lints here. I'll whip up a quick fix PR.

**Comment by MichaelChirico** [comment]
For `tests/testthat/test-error.R` we'd have to either extract with `:::` or re-define it, is it worth it?

**Comment by AshesITR** [comment]
Using internal functions in tests seems okay to me.

**Comment by MichaelChirico** [comment]
OK done

**Review by AshesITR — APPROVED** [review]
LGTM

**Pull request merged**
