### PR TITLE
Add equals_na_linter

### LINKED ISSUE #143: x == NA instead of is.na(x)
It would be useful to have a linter that checks for `x == NA` where I meant to write `is.na(x)`. Is that possible?

### PR DESCRIPTION
**Pull request by jabranham**
Adds a linter that checks for e.g. `x == NA` rather than `is.na(x)`. Added to default linters.

Let me know if something isn't clear or if I need to change something.

Closes #143

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks! Could you add a note to NEWS.md mentioning this addition with your GitHub handle and the issue number?

**Comment by jabranham** [comment]
Sure, done. I also regenerated the documentation. 

Just FYI, the NEWS.md file starts with `1.0.1.9001`, but that's smaller than what's in DESCRIPTION, which says `1.0.2.9000`.

**Comment by jimhester** [comment]
It is just outdated in the NEWS file and needs to be updated.

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
