### PR TITLE
[#118] fix a bug of `commented_code_linter`: commented code inside roxygen docs

### PR DESCRIPTION
**Pull request by yu-iskw**
https://github.com/jimhester/lintr/issues/118

### CODE REVIEW

**Comment by yu-iskw** [comment]
@jimhester could you review it when you have time?

**Comment by jimhester** [comment]
I think this is already working as intended,
```r
#' foo(bar, 2L) # foo(1, 2)
```
Should have a lint for the `# foo(1, 2)` as that is commented code, why do you think it should not be linted?

**Comment by yu-iskw** [comment]
For example, when I run the test on master, I got an error.

```
  expect_lint("#' blah <- 1 # 1 + 1",
    NULL,
    commented_code_linter)
```

```
commented_code_linter : ...../var/folders/j0/7y3gvsjn0bgbyfgj7dhqf0580000gn/T//RtmpuRSO1v/file47fde56a20b:1:16: style: Commented code should be removed.
#' blah <- 1 # 1 + 1
               ^~~~~
....
1. Failure: returns the correct linting ----------------------------------------
commented_code_linter returned list(filename = "/var/folders/j0/7y3gvsjn0bgbyfgj7dhqf0580000gn/T//RtmpuRSO1v/file47fde56a20b", line_number = 1, column_number = 16, type = "style", message = "Commented code should be removed.", line = "#' blah <- 1 # 1 + 1", ranges = list(c(16, 20)), linter = "commented_code_linter") lints when it was expected to return none!
```

**Comment by jimhester** [comment]
`# 1 + 1` is also valid commented code and should produce a lint. Again why are you expecting these not to do so?

**Comment by yu-iskw** [comment]
I think we shouldn't produce a lint if a commented code is in roxygen docs.

**Comment by jimhester** [comment]
Why not?

**Comment by fangly** [comment]
Commented code outside a roxygen section is presumably be stale code that is not current anymore, remains from debugging or throaway code generated to test an idea, etc... One may justifiably want to lint such commented code.

On the other hand, the goal of a roxygen section is to document something and any commented code within a roxygen section serves this purpose of documentation as well. Thus, I agree with @yu-iskw on this issue and my inclination would be to _not lint commented code within roxygen sections_.

**Comment by naught101** [comment]
Code in an `@example` section in roxygen is particularly legit..

**Pull request closed without merging**
