### PR TITLE
spaces_inside_linter ignores trailing comments

### LINKED ISSUE #636: spaces_inside_linter doesn't ignore trailing comments
Found in the course of working on #598 

```
writeLines("
lm( # cool regression
 y ~ x
)
", tmp <- tempfile())

lintr::lint(tmp, lintr::spaces_inside_linter)
# /tmp/RtmpAD3BJR/file41eb53c52da:2:4: style: Do not place spaces around code in parentheses or square brackets.
# lm( # cool regression
#    ^
```

trailing whitespace should be ignored if there is no code after the the `(`.

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #636

### CODE REVIEW

**Review by AshesITR — DISMISSED** [review]
LGTM, thanks for catching!

**Comment by MichaelChirico** [comment]
this darn travis thing. going to close this PR & reopen on a dummy branch

**Comment by MichaelChirico** [comment]
@jimhester sorry for the bother... searched around a bit, maybe you could remove travis from branch protection?

https://github.com/jazzband/pip-tools/pull/1229#issue-524812971

**Review by AshesITR — APPROVED** [review]

**Comment by AshesITR** [comment]
Looks like the build failures actually expose a bugged edge-case: Multiple spaces still cause a lint.

**Review by AshesITR — CHANGES_REQUESTED** [review]
Need to fix for multiple trailing spaces followed by `#` as well.

**Comment by MichaelChirico** [comment]
good catch; fixed

**Review by AshesITR — APPROVED** [review]
LGTM

**Pull request merged**
