### PR TITLE
Respect "# nolint" comments with caching

### LINKED ISSUE #68: Caching and # nolint
The `# nolint` comments don't seem to work properly with caching. They are respected only on first execution (presumably, when the cache is dirty) -- from the second execution onwards, errors are reported.

Try

```
lintr::lint_package(".", cache = TRUE)
```

for [my package](https://github.com/krlmlr/kimisc).

### PR DESCRIPTION
**Pull request by krlmlr**
- includes test

Fixes #68.

### CODE REVIEW

**Comment by jimhester** [comment]
Thank a lot for adding a test for this Kirill, very helpful!

**Comment by krlmlr** [comment]
Well... the test was supposed to fail, it was pushed before the fix. Also, I'm not sure -- could the `clear_cache()` call introduce a race condition or something?

**Comment by krlmlr** [comment]
I think Travis CI got the wrong revision for this particular test. I'll create a bogus pull to test the test.

**Comment by jimhester** [comment]
The main issue I could see with using `clear_cache()` with no arguments is it will clear the entire cache for all files.

It would probably be better to use `clear_cache("exclusions-test")` to only clear the cache for that file.

**Pull request merged**
