### PR TITLE
Replace igraph calls with our own R code, get rid of igraph

### PR DESCRIPTION
**Pull request by gaborcsardi**
It is also faster, at least the complicated QC.R case. I also profiled it for this file, it is as fast as it gets, `self.time: 0.00`, `self.pct: 0.00`. :)

### CODE REVIEW

**Comment by gaborcsardi** [comment]
This closes #151.

**Comment by jimhester** [comment]
Looks great, could you add a note to NEWS.md then I will happily merge.

**Comment by gaborcsardi** [comment]
I am not sure what you want in the NEWS, nothing has changed in the API, right? Just that it is not depending on igraph now?

**Comment by jimhester** [comment]
Yeah just mentioning the dependency is removed is fine.

I don't typically restrict NEWS mentions to just API changes, but maybe that is a good practice...

**Comment by gaborcsardi** [comment]
OK, added the bullet point to the NEWS. Thanks!

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
