### PR TITLE
Simplify getting started

### PR DESCRIPTION
**Pull request by krlmlr**
Please feel free to change wording. Adding this as a supported function to the package is probably too much.

Ref: https://github.com/jimhester/lintr/issues/73#issuecomment-90927745

### CODE REVIEW

**Comment by jimhester** [comment]
Could also use `%$%` instead of the curly brackets, makes things a little simpler, although perhaps more obscure.

```r
library(dplyr)
lintr::lint_package() %>%
  as.data.frame %>%
  group_by(linter) %>%
  tally(sort = TRUE) %$%
  sprintf("with_defaults(\n  %s\n  NULL\n)",
          paste0(linter, " = NULL, # ", n, collapse="\n  ")) %>%
  cat(file = ".lintr")
```

**Comment by krlmlr** [comment]
Thanks. Your code works for me, too. Updated PR.

(I'm not yet convinced about `%$%`. A big advantage of `magrittr` is that code is not only easy to write but also easy to maintain. Imagine I wanted to add a step after the `tally` call -- I have to remember that `%$%` is logically bound to the next step. That's why I personally prefer the `with` syntax. Something like the following would be better:

```
lintr::lint_package() %>%
  as.data.frame %>%
  group_by(linter) %>%
  tally(sort = TRUE) %>%
  expose %>%
  sprintf("with_defaults(\n  %s\n  NULL\n)",
          paste0(linter, " = NULL, # ", n, collapse="\n  ")) %>%
  cat(file = ".lintr")
```
)

**Comment by jimhester** [comment]
That is fair, I am not sure I am sold on `%$%` myself.  I think using `with` as you did might be the most desirable as it keeps the internal variable exposure contained to the single statement.

I will merge this as is however, for a simple one off script I think the succinctness of `%$%` somewhat beneficial.

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
