### PR TITLE
add T_and_F_symbol_linter to default_linters

### LINKED ISSUE #517: Add T and F symbol linter to default linters?
The tidyverse style guide forbids `T` and `F` as shorthand for `TRUE` and `FALSE` (cf. https://style.tidyverse.org/syntax.html#logical-vectors)
Maybe we should add the corresponding linter to the list of default linters?

### PR DESCRIPTION
**Pull request by AshesITR**
delint zzz.R and remove unnecessary # nolint in the same file

also fix the minor issue #511 while touching zzz.R

fixes #517 and #511

### CODE REVIEW

**Comment by AshesITR** [comment]
Trying to close & re-open as new to see if travis disappears.

**Comment by AshesITR** [comment]
#629 should appease codecov.

**Review by MichaelChirico — APPROVED** [review]

**Comment by AshesITR** [comment]
grafik
Very curious...

**Comment by MichaelChirico** [comment]
maybe you have higher privileges than me, though I didn't think github had
so many access levels

**Comment by AshesITR** [comment]
@MichaelChirico This one had a merge conflict in NEWS.md.
Can you re-approve? Thanks!

I'll create an issue WRT auto-merging for NEWS.md.

**Review by MichaelChirico — APPROVED** [review]

**Pull request merged**
