### PR TITLE
Make sprintf_linter capture warnings

### LINKED ISSUE #624: sprintf_linter causes test warning on r-devel
https://travis-ci.org/github/jimhester/lintr/jobs/746547257#L1728

```
── Warning (test-sprintf_linter.R:7:3): returns the correct linting ────────────

one argument not used by format 'hello'

── Warning (test-sprintf_linter.R:43:3): returns the correct linting ───────────

one argument not used by format 'hello %1$s %s'

── Warning (test-sprintf_linter.R:47:3): returns the correct linting ───────────

one argument not used by format 'hello %1$s %1$s'
```

Should catch the warning in the linter using `withCallingHandlers` and turn it into a lint.

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #624

### CODE REVIEW

**Review by renkun-ken — DISMISSED** [review]
LGTM. Thanks for capturing and fixing this.

**Comment by AshesITR** [comment]
As an added bonus, this should lint for unused arguments now on r-devel.
I expect the current test to fail because of that, though.

**Comment by renkun-ken** [comment]
Not sure if a new issue should be raised. The `sprintf_linter` will complain about the following code:

```r
f <- function(id, ...) {
  sprintf("%d %d, %d", id, ...) ### to few arguments
}
```

since `...` is regarded as typical symbol and replaced with `0` before eval. Any idea how we should handle this with currentl implementation?

**Comment by AshesITR** [comment]
Good catch - definitely worth an issue since I don't immediately see how to find out the required cardinality of `...` without writing a proper parser.

NB that a call like `f(42, fmt = "bla")` can really mess things up in the example.
I'd generally consider it a bad idea to put a fixed format string together with `...`. Maybe not worth fixing.

**Review by renkun-ken — APPROVED** [review]
LGTM

**Pull request merged**
