### PR TITLE
lintr:::print.lint issue

### PR DESCRIPTION
**Pull request by jamieRowen**
fixed an issue that caused a
Error in rep.int(character, length) : invalid 'times' value
that caused an issue when printing results from the single_quotes_lintr
It was assumed in highlight_string that the range was such that
range[1] < range[2] which is not necessarily the case when
the string is split over a new line. Added a test case for this
too.

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks! Can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`. Then I can merge this.

**Comment by jamieRowen** [comment]
Done, no issue number attached as don't think it was raised prior, just came across it earlier today

**Comment by jimhester** [comment]
Thanks! 

Thanks a million!

**Comment by jamieRowen** [comment]
No worries, it's a pleasure

**Pull request merged**
