### PR TITLE
merge NEWS.md with union

### LINKED ISSUE #655: `NEWS.md` should be auto-mergeable
Needs a `.gitattributes` file with these contents:

```
NEWS.md -text merge=union
```

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #655

### CODE REVIEW

**Comment by MichaelChirico** [comment]
have you tested this locally?

I didn't get around to it but I was going to create two test branches locally and try to merge them to one another to test it actually works

**Comment by AshesITR** [comment]
Haven't yet but if master changes, this PR can self-test I think.

**Comment by AshesITR** [comment]
Couldn't test today but it should work.
I'll confirm once I tested something similar locally.

**Comment by MichaelChirico** [comment]
I don't think there's any harm in merging but still preferable to test it
if possible

**Comment by MichaelChirico** [comment]
Tested with:

```
insert_at() {
  head -n $2 $1 > tmp
  echo "$3" >> tmp
  tail -n +$(($2 + 1)) $1 >> tmp
  mv tmp $1
}

git checkout -b test-merge-1

# 26 by inspection
insert_at 'NEWS.md' 26 '* WE DID THIS THING'
git commit -am 'test NEWS'

git checkout master
git checkout -b test-merge-2

echo "NEWS.md text merge=union eol=lf" >> .gitattributes
insert_at 'NEWS.md' 26 '* WE DID ANOTHER THING'
git commit -am 'another test'

# this will pull up EDITOR
git merge test-merge-1

git checkout master
git checkout -b test-merge-3

insert_at 'NEWS.md' 26 '* WE DID A THIRD THING'
git commit -am 'placebo test'

# merge fails because .gitattributes missing in these two branches
git merge test-merge-1
```

**Review by MichaelChirico — APPROVED** [review]

**Pull request merged**
