### PR TITLE
Simplify line length

### PR DESCRIPTION
**Pull request by MichaelChirico**

### CODE REVIEW

**Review by AshesITR — COMMENTED** [review]
Just a quick thought: Wouldn't setting `column_number = length + 1` be more convenient for breaking up the line?

**Comment by MichaelChirico** [comment]
I think this is a more general issue... in my mind the `ranges` is used to highlight the lint:

```
a_really_long_line_according_to_20_characters
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

which if we go to column+1 will look odd for that use case...

vs the use case you have in mind, which is to land the cursor just _after_ the lint when using it with the rstudio plugin.

Can we make these two use cases work together better?

**Comment by AshesITR** [comment]
How would the highlight look if the range is left in tact (1 to nchar) and the column_number updated?

**Comment by MichaelChirico** [comment]
Oh sorry, I misunderstood. IIUC the `^~~~` tag is only built from ranges. So `column_number` should be fine to update. But perhaps best to keep as a follow-up to keep the PR more focused.

**Comment by AshesITR** [comment]
Thats fine by me.

**Review by AshesITR — APPROVED** [review]

**Pull request merged**
