### PR TITLE
Anchor to opening brace instead of closing paren in paren_brace_linter

### LINKED ISSUE #583: curly_brace_linter column number is sub-optimal
Lints for code like

```r
fun <- function(){
  42L
}
```

Currently have the location of the curly brace lint at the closing parenthesis.
If it were moved to the opening curly brace, clicking the lint in RStudio Markers pane would put the cursor at just the right spot to insert the missing space.

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #583

- [x] implement
- [ ] update tests to check lint location as well

### CODE REVIEW

**Comment by AshesITR** [comment]
We could potentially test explicitly for the column number of the lints in tests, WDYT?

**Review by MichaelChirico — APPROVED** [review]
LGTM, glad it's an easy fix. XPath can be great!

**Comment by MichaelChirico** [comment]
I'm not sure it's always ideal, but in this case I would say it's a good idea to test since the issue is explicitly about getting a better position from the linter

**Comment by AshesITR** [comment]
Okay, I'll work on that tomorrow maybe.
Fixed the XPath reversal (I overlooked the intermediate `expr`)

**Review by MichaelChirico — APPROVED** [review]

**Pull request merged**
