### PR TITLE
New pipe_call_linter enforcing calls (not symbols) in magrittr pipes

### PR DESCRIPTION
**Pull request by MichaelChirico**
This enforces the following section of the tidyverse style guide:

https://style.tidyverse.org/pipes.html#no-arguments

### CODE REVIEW

**Comment by AshesITR** [comment]
Looks good so far. Can we also add a negative test for

```
x %>% { foo }
```

just to be sure symbols are allowed in curly braces?

**Comment by MichaelChirico** [comment]
does that code actually do anything?

**Comment by AshesITR** [comment]
This minimal code returns foo from the chain.
However, if this is correctly not linted, more complex code blocks should also be covered - e.g.

```
x %>% {
  tmp <- .
  bla <- foo %>% unrelated_stuff(tmp)
  my_combination_fun(tmp, bla)
}
```

**Comment by MichaelChirico** [comment]
that looks more reasonable to test as a minimal usage example. I'll test &
add it tomorrow.

**Comment by MichaelChirico** [comment]
Updated now. Thanks!

**Review by AshesITR — APPROVED** [review]

**Pull request merged**
