### PR TITLE
Fix some regex-based linters getting spurious matches

### LINKED ISSUE #441: `paren_brace_linter` false positive within regex strings: "(match_group){quantifier}"
`paren_brace_linter` flags the "){" within regex definition below:

```
#' Checks if a file has a .tar or .tar.bz2 extension
#'
#' @noRd
.is_tar_file <- function(x) {
  grepl(pattern = ".*\\.tar(\\.bz2){0,1}", x)
}
```

Should `paren_brace_linter` be made more strict - so that it doesn't consider strings?

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #441 

Forked from #467 -- re-filing with the base branch on the main repo (cc @russHyde)

### CODE REVIEW

**Comment by MichaelChirico** [comment]
For now I'll leave this as is on the assumption that #546 would be merged first. After that, I would keep the tests for `equals_na_linter` from here.

**Comment by MichaelChirico** [comment]
The same issue as #546 (about the XML tree being missing when there's a syntax error) was hitting `equals_na_linter` in this branch, so I just went ahead and reverted that part. First, I copied the tests over there as well.

**Review by AshesITR — APPROVED** [review]
LGTM

**Review by AshesITR — DISMISSED** [review]
Thanks for resurrecting this PR!

**Review by AshesITR — DISMISSED** [review]

**Review by AshesITR — APPROVED** [review]

**Pull request merged**
