### PR TITLE
Support lambda syntax in spaces_left_parentheses_linter

### LINKED ISSUE #685: Treat lambda as function in spaces_left_parentheses_linter
In r-devel, `spaces_left_parentheses_linter` complains about the newly introduced lambda syntax where `\(x)` is equivalent with `function(x)`.

```r
> lintr::lint("\\(x) x + 1\n")                                                                                                                                                                                                                            
<text>:1:2: style: Place a space before left parenthesis, except in a function call.
\(x) x + 1
 ^
```

### PR DESCRIPTION
**Pull request by renkun-ken**
Closes #685

### CODE REVIEW

**Comment by MichaelChirico** [comment]
I am a bit hesitant to merge this so soon

> These features are experimental and may change prior to release.

if we release and R changes something before release that would be unfortunate no?

if we are going to release soon I would at least wait for that and maybe merge this as first PR on next dev version

**Comment by renkun-ken** [comment]
Yes, I agree. They say that the feature is experimental and subject to change before release. I guess we better wait for the r-devel to move on.

**Comment by AshesITR** [comment]
Could you convert this to a draft to avoid accidental merging?

**Comment by IndrajeetPatil** [comment]
With `R 4.1.0` now out, maybe this can be reconsidered?

**Comment by renkun-ken** [comment]
I guess it is time now.

**Comment by renkun-ken** [comment]
Looks like the latest implementation of `spaces_left_parentheses_linter` already works with lambda.

**Comment by renkun-ken** [comment]
Closing as not needed.

**Pull request closed without merging**
