### PR TITLE
lint_package returns early when no package is found

### PR DESCRIPTION
**Pull request by MichaelChirico**
On HEAD this gives me a funny error:

```
lintr::lint_package("/")
# Error in paths[rel_path] <- file.path(root, paths[rel_path]) : 
#   replacement has length zero
```

Should we issue a warning here?

### CODE REVIEW

**Comment by AshesITR** [comment]
Shouldn't this be an error condition?

**Comment by MichaelChirico** [comment]
An error seems harsh, though maybe the return should just be NULL?

Ran into this trying to create a test for #702  -- easiest test is to make sure a `DESCRIPTION` directory is skipped and then no package is found at all.

**Comment by AshesITR** [comment]
I would return NULL for `find_package` but `lint_package()` run non-interactively IMO should definitely error if there was no package, no?

If not, a warning ("No package was found at '/path'."?) with `NULL` instead of an empty `lints()` seems more correct.
Maybe even something like `NA` such that `length(lint_package())` will be different from the lint-free state.

**Comment by MichaelChirico** [comment]
I'm still happy with warn + return `NULL`. Don't really like `NA` -- the `warning` should be enough to distinguish from lint-free right?

Also it's `NULL` whereas lint-free is `list()`.

**Review by AshesITR — CHANGES_REQUESTED** [review]
LGTM. Please add a NEWS bullet.

**Review by AshesITR — APPROVED** [review]

**Pull request merged**
