### PR TITLE
Clarify seq_linter message

### LINKED ISSUE #522: Error message for seq_linter.R
Error message for seq_linter is slightly unclear - it implies that nrow() is not allowed.  

(I will provide suggestion for revision later.)

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #522

I think basically we need to convey why seq_len is being suggested. I opted for a succinct version that works for all of the `bad_funcs` covered here. I think we could do better with a longer message, but I don't know how much you prefer the messages as terse as possible.

### CODE REVIEW

**Comment by AshesITR** [comment]
NB `rex()` auto-escapes text, so the test fixes are broken, because the actual regex contains `\.\*` instead of `.*`.

**Comment by jimhester** [comment]
you can use the `anything` shortcut to insert `.*` in the rex expression.

**Comment by MichaelChirico** [comment]
Thanks for the `rex` pointers, it's passing now

**Review by AshesITR — APPROVED** [review]

**Comment by jimhester** [comment]
Can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by MichaelChirico** [comment]
NEWS added

**Comment by jimhester** [comment]
Thanks a watt!

**Pull request merged**
